TestMVCProject/Models/AddEntityDataVM.cs
namespace TestMVCProject.Models
{
    public class AddEntityDataVM
    {
        public string Name { get; set; } = string.Empty;
        public string Surname { get; set; } = string.Empty;
        public int Age { get; set; }
    }
}

TestMVCProject/Models/Domain/EntityModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestMVCProject.Models.Domain
{
    public class EntityModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Surname { get; set; } = string.Empty;
        public int Age {  get; set; }
    }
}

TestMVCProject/Models/ErrorViewModel.cs
namespace TestMVCProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestMVCProject/Models/ViewEntityDataVM.cs
namespace TestMVCProject.Models
{
    public class ViewEntityDataVM
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Surname { get; set; } = string.Empty;
        public int Age { get; set; }
    }
}

TestMVCProject/Controllers/EntityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TestMVCProject.Data;
using TestMVCProject.Models;
using TestMVCProject.Models.Domain;

namespace TestMVCProject.Controllers
{
    public class EntityController : Controller
    {
        private readonly ApplicationDbContext _context;
        public EntityController(ApplicationDbContext context)
        {
            this._context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var data = await _context.EntityModels.ToListAsync();
                return View(data);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                throw;
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddEntityDataVM data)
        {
            try
            {
                var model = new EntityModel()
                {
                    Name = data.Name,
                    Surname = data.Surname,
                    Age = data.Age
                };
                await _context.EntityModels.AddAsync(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                throw;
            }
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var userInfo = await _context.EntityModels.FirstOrDefaultAsync(x => x.Id.Equals(id));
                if (userInfo is null)
                    return RedirectToAction("Index");
                var data = new ViewEntityDataVM()
                {
                    Name = userInfo.Name,
                    Surname = userInfo.Surname,
                    Age = userInfo.Age
                };
                return View(data);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EntityModel data)
        {
            try
            {
                var userInfo = await _context.EntityModels.FirstOrDefaultAsync(x => x.Id.Equals(data.Id));
                if (userInfo is null)
                    throw new Exception($"Data not found.");
                 _context.EntityModels.Remove(userInfo);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                throw;
            }
        } 
        [HttpPost]
        public async Task<IActionResult> Search(string Name)
        {
            try
            {
                Name = "Hamza";
                var userInfo = await _context.EntityModels.Where(x => x.Name.Contains(Name)).ToListAsync();
                if (userInfo is null)
                    throw new Exception($"Data not found.");
                return View(userInfo);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                throw;
            }
        }
        
        public IActionResult Services()
        {
            return View();
        }

    }
}

TestMVCProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestMVCProject.Models;

namespace TestMVCProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestMVCProject/Views/Entity/Add.cshtml
@model TestMVCProject.Models.AddEntityDataVM
@{
}
<h1>Add Entity</h1>
<form method="post", action="Add">
    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="form-group">
        <label for="">Surame</label>
        <input type="text" class="form-control" asp-for="Surname">
    </div>
    <div class="form-group">
        <label for="">Age</label>
        <input type="number" class="form-control" asp-for="Age">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TestMVCProject/Views/Entity/Details.cshtml
@model TestMVCProject.Models.ViewEntityDataVM

<h1>View User</h1>
<form method="post" , action="Details">
    <div class="form-group">
        <label for="">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div><div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name" readonly>
    </div>
    <div class="form-group">
        <label for="">Surname</label>
        <input type="text" class="form-control" asp-for="Surname" readonly>
    </div>
    <div class="form-group">
        <label for="">Age</label>
        <input type="number" class="form-control" asp-for="Age" readonly>
    </div>

    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Entity">Delete</button>
</form>

TestMVCProject/Views/Entity/Index.cshtml
@model IEnumerable<TestMVCProject.Models.Domain.EntityModel>

<h1>Data</h1>

@using (Html.BeginForm("Search", "Entity", FormMethod.Post, new { @class = "form-inline" }))
{
   <table>
       <tr>
           <td>
                @Html.TextBox("Name", null, new { Class = "form-control", placeholer = "Enter name" })
           </td>
           <td>
               <input type="submit" value="search" class="btn btn-success" />
           </td>
       </tr>
   </table>
}



<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Age</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.Age</td>
                <td><a href="Details/@item.Id">View</a></td>
            </tr>
        }
    </tbody>
</table>

TestMVCProject/Views/Entity/Search.cshtml
@model IEnumerable<TestMVCProject.Models.Domain.EntityModel>

<h1>Search Results</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Age</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.Age</td>
                <td><a href="Details/@item.Id">View</a></td>
            </tr>
        }
    </tbody>
</table>

TestMVCProject/Views/Entity/Services.cshtml
<h1>Entity Framework Operations</h1>

<a href="Add/">Add Data</a>
<a href="Index/">Get Data</a>

TestMVCProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestMVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestMVCProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestMVCProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestMVCProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Services
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" asp-action="Services" asp-controller="Entity">Save Data with Entity</a></li>
                                    <li><a class="dropdown-item" href="https://localhost:7097/swagger/index.html">Save Data with Web Service</a></li>
                                </ul>
                            </div>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestMVCProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>